# golangci-lint configuration for pgn-extract-go
# Docs: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  concurrency: 0
  allow-parallel-runners: true

linters:
  default: none
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Bug detection
    - bodyclose
    - durationcheck
    - nilerr
    - noctx
    # Code style
    - misspell
    # Complexity
    - cyclop
    - gocognit
    - nakedret
    # Error handling
    - errorlint
    # Performance
    - prealloc
    # Security
    - gosec

  settings:
    cyclop:
      max-complexity: 35
      package-average: 15.0

    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - (io.Closer).Close
        - (*os.File).Close
        - os.Remove
        - os.RemoveAll
        - (fmt.State).Write
        - (*bytes.Buffer).Write
        - (*bytes.Buffer).WriteString
        # Logging functions - errors rarely actionable
        - fmt.Fprint
        - fmt.Fprintln
        - fmt.Fprintf
        - fmt.Print
        - fmt.Println
        - fmt.Printf
        # JSON encoding to writer - errors handled via writer
        - (*encoding/json.Encoder).Encode
        # Parsing functions where default value is acceptable
        - fmt.Sscanf
        - strconv.Atoi
        # Tag matching - only fails for OpRegex, callers use known-safe ops
        - (*github.com/lgbarn/pgn-extract-go/internal/matching.TagMatcher).AddCriterion

    gocognit:
      min-complexity: 50

    gosec:
      includes:
        - G101
        - G102
        - G103
        - G104
        - G106
        - G107
        - G108
        - G109
        - G110
        - G201
        - G202
        - G203
        - G204
        - G301
        - G302
        - G303
        - G304
        - G305
        - G306
        - G401
        - G402
        - G403
        - G404
        - G501
        - G502
        - G503
        - G504
        - G505

    govet:
      enable-all: true
      disable:
        - fieldalignment

    misspell:
      locale: US
      extra-words:
        - typo: colour
          correction: colour
        - typo: Colour
          correction: Colour
        - typo: coloured
          correction: coloured
        - typo: Encyclopaedia
          correction: Encyclopaedia

    nakedret:
      max-func-lines: 30

    prealloc:
      for-loops: true
      range-loops: true
      simple: true

    staticcheck:
      checks:
        - all

    unused:
      exported-fields-are-used: true

  exclusions:
    rules:
      # Don't check errors in test files - test code often intentionally ignores errors
      - path: ".*_test\\.go$"
        linters:
          - errcheck
          - gosec
      # Exclude cyclop for the lexer - it's inherently complex
      - path: internal/parser/lexer.go
        linters:
          - cyclop
      # AddCriterion only returns error for OpRegex; all other callers use safe operators
      - source: "\\.AddCriterion\\("
        linters:
          - gosec

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/lgbarn/pgn-extract-go
